"""create table short_url

Revision ID: b4d8735188e6
Revises: 
Create Date: 2021-07-04 01:15:42.068841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d8735188e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.String(256), nullable=False),
    sa.Column('shorted_key', sa.String(256), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shorted_key')
    )
    op.create_index('ShortUrl_shorted_key_idx', 'short_url', ['shorted_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ShortUrl_shorted_key_idx', table_name='short_url')
    op.drop_table('short_url')
    # ### end Alembic commands ###
